### ISSUE TITLE
JetBrains 2020 Support

### ISSUE THREAD

**Issue by johnsintal** [bchatard/alfred-jetbrains#115]
**Describe the bug**
Out of the box, this great workflow has issues with ppl using the EAP of Jetbrain Products, like Webstorm 2020.1 EAP.

According to their site, 2020.1 and above versions and 2019.3.x and below versions use difference preference folder locations on mac.

I fixed this by moving overriding the idea.properties file like for example
```
# custom RubyMine properties
idea.config.path=~/Library/Preferences/RubyMine2020.1/
```

It would be nice if this was supported out of the box. It took me hours debugging the issue and finally resolving it. 

To replicate, simply install the 2020 EAP of your a product that doesn't already exist on mac and try to find a project. It will throw an error indicating preference file could not be found.

**Additional context**
[source](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)
![image](https://user-images.githubusercontent.com/2457368/78468736-8ab79a00-76e8-11ea-9818-a877afd7adc2.png)

**Comment by bchatard** [comment]
Hi,

Thanks for your complete feedback about this.
This tools is used for my daily work with at least 3 JetBrains products, and I work only with stable release. An issue as been already opened for EAP / RC support in parallel of stable.

Your analysis will help me a lot when 2020 will be released. I also notice that 2019 and 2020 doesn’t share the same configuration folder so support for both path will be necessary.

If you have some times maybe you can start a MR for supporting both path ?

Again thanks for your help !

**Comment by bchatard** [comment]
Hi,

Webstorm 2020 released, so I update the workflow (v1.3.0). Can you take a look on it?

**Comment by johnsintal** [comment]
I am setting up a new dev env next week , so I will see if this fixes the problem I had. I don't want to mess w/ my current configuration on this laptop.

**Comment by johnsintal** [comment]
Fresh install Mac, Rubymine and Webstorm, I also installed your latest version and I am getting an error

Fresh install Mac, Rubymine and Webstorm, I also installed your latest version and I am getting an error

For Rubymine
```
Error: Can't find 'options' XML in /Users/jsyntax/Library/Application Support/JetBrains/WebStorm2020.1
    at Object.getProjectPaths [as get] (/Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:83:9)
    at Object.getItems (/Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)
    at /Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23
    at Object.<anonymous> (/Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/Users/jsyntax/.nvm/versions/node/v10.15.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```

-
JetBrains - Open Project - v3 1.3.1
Alfred 4.0.9
darwin 19.4.0


## For Webstorm
It works!

**Comment by bchatard** [comment]
hi @johnsintal 

thanks for your feedback.
I will add `rubymine` & `mine` as bin name for RubyMine
