### ISSUE TITLE
ReferenceError: bin is not defined - While opening PHPStorm 2020.1

### ISSUE THREAD

**Issue by pedro-stanaka** [bchatard/alfred-jetbrains#126]
Q | A
--- | ---
Workflow version | v3 1.3.1
OSX Version | 10.15.4
Alfred Version | 4.0.9
JetBrains Product/Version | PhpStorm / 2020.1
Installation type | npm

### Description
After update of the workflow I started getting the error:

```
ReferenceError: bin is not defined
    at getApplicationPath ($NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:145:54)
    at Object.get ($NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:155:31)
    at $NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> ($NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> ($NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at $NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl ($NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl ($NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u ($NODE_PATH/.npm/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```

-
JetBrains - Open Project - v3 1.3.1
Alfred 4.0.9
darwin 19.4.0

### Step to reproduce
Just type `<phpstorm keyword> ` on alfred and watch the error.

**Comment by bchatard** [comment]
pretty weird I use it since the release of 2020 products, and never see this error, but your PR should fix the issue

**Comment by bchatard** [comment]
I got the error too now, it's related to 1.17 Toolbox version...

**Comment by bchatard** [comment]
version 1.3.2 released! thanks again for your PR!

**Comment by pedro-stanaka** [comment]
Thanks for the rapid response!
