### ISSUE TITLE
Can't open AppCode 2020.1

### ISSUE THREAD

**Issue by AlexeyKorshun** [bchatard/alfred-jetbrains#129]
Try to open AppCode 2020.1 by typing `appcode `

```
TypeError: Cannot read property 'length' of null
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:129:29)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:157:31)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.3.2_                                |
| OSX Version               | _10.15.4_                              |
| Alfred Version            | _4.0.9_                                  |
| JetBrains Product/Version | _AppCode / 2020.1_                    |
| Node version              | _10.15.3_ (`node --version`)            |
| NPM version               | _6.9.0_ (`npm --version`)              |

**Comment by bchatard** [comment]
hello,

Thanks for your report
It's fixed in 1.3.3

**Comment by AlexeyKorshun** [comment]
right now it reproduce for android studio to.

**Comment by AlexeyKorshun** [comment]
@bchatard Yeah. Thx, it doesn't reproduce in 1.3.3.
