### ISSUE TITLE
Error: Can't find application path for PyCharm|DataGrip

### ISSUE THREAD

**Issue by netgitdom** [bchatard/alfred-jetbrains#131]
**Describe the bug**
I updated to 1.3.3 and got this message

```
Error: Can't find application path for PyCharm.
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:147:9)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:157:31)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```
-
JetBrains - Open Project - v3 1.3.3
Alfred 4.0.9
darwin 18.7.0

It worked flawlessly all the time. The Shellscripts which were generated by the JetBrainsToolbox are working if I start them. 
I have no Environvariables set in the Alfred-plugin

**To Reproduce**
Start Alfred by hotkey
type "pycharm"
choose "Open PyCharm Project"
Wait second and then the error appears.

**Expected behavior**

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.3.3_                                |
| OSX Version               | _10.14.6_                              |
| Alfred Version            | _4.0.9_                                  |
| JetBrains Product/Version | PyCharm / 2019.3_                    |
| Installation type         | _JB Toolbox_ |
| Node version              | _13.1.0_ (`node --version`)            |
| NPM version               | _6.12.1_ (`npm --version`)              |

**Comment by bchatard** [comment]
Hi 

thanks for your report, please check version 1.3.4

**Comment by netgitdom** [comment]
Hi,

I just installed the update and it is working again. That was fast. Thank you very much :-)

Regards
