### ISSUE TITLE
Question about First Execution

### ISSUE THREAD

**Issue by spearkkk** [bchatard/alfred-jetbrains#161]
Q | A
--- | ---
Workflow version | _1.4.0_
OSX Version | _10.15.6_
Alfred Version | _4.1.1_
JetBrains Product/Version | idea ultimate / 2020.2
Installation type | _classic .dmg

### Description
There is a error message if there is no recent project  or something.
I just wonder whether it is normal action or not.

1. I just installed IDEA.
2. And installed this workflow and then triggered.
3. But I got a error message:
```
Error: Can't find 'options' XML in /Users/something_user_name/Library/Application Support/JetBrains/IntelliJIdea2020.2
    at Object.getProjectPaths [as get] (/Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:83:9)
    at Object.getItems (/Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)
    at /Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23
    at Object.<anonymous> (/Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/Users/something_user_name/.nvm/versions/node/v12.18.3/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```

Actually, I read `project/paths.js` file and find logic that error is thrown if there is no recent data in `options` directory.
So I just opened some project and closed.
And then **I tried to trigger this workflow and it works**.

I just want to know that is it known issue?
Thanks, I appreciate your nice sharing.

### Step to reproduce
...

**Comment by bchatard** [comment]
hi,

yes it can be a bug :) actually I always presume some projects before installing this workflow, but your use case is correct.

I will try to add a message for that case, or maybe you ;)

**Comment by spearkkk** [comment]
@bchatard  Thank you.
If you add message for this status, it can be helpful.
I always thank you and your sharing.
This workflow is sooo nice !

**Comment by wellsemon** [comment]
same error, any update now?

**Comment by wellsemon** [comment]
operation steps not same with spearkkk.
change config throght Jetbrains ToolBox, recent projects xml now located in new folder, not default.
Is it reason?
