### ISSUE TITLE
Can't find preference for android studio

### ISSUE THREAD

**Issue by AlexeyKorshun** [bchatard/alfred-jetbrains#169]
**Check [Troubleshooting](/doc/troubleshooting.md) first**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.4.0_                                |
| OSX Version               | _10.15.7_                              |
| Alfred Version            | _4.2_                                  |
| JetBrains Product/Version | _Android Studio 4.1    |
| Installation type         | _classic .dmg / Caskroom / JB Toolbox_ |
| Node version              | _10.15.3_ (`node --version`)            |
| NPM version               | _6.14.5_ (`npm --version`)              |

**Additional context**
```
Error: Can't find preference path for AndroidStudio
    at getPreferencePath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:97:9)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:156:30)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```

-
JetBrains - Open Project - v3 1.4.0
Alfred 4.2
darwin 19.6.0

**Comment by bchatard** [comment]
Hi,

Can you provide the result of this commands: 
* `ls -hAl ~/Library/Application\ Support/JetBrains/`
* `s -dhAl ~/Library/Preferences/*/`

Thanks,

**Comment by AlexeyKorshun** [comment]
```
ls -hAl ~/Library/Application\ Support/JetBrains/
total 16
drwxr-xr-x  14 alekseikorshun  staff   448B Aug 27 19:53 AppCode2020.1
drwxr-xr-x  15 alekseikorshun  staff   480B Nov 11 22:53 AppCode2020.2
drwxr-xr-x  16 alekseikorshun  staff   512B Aug  4 11:06 IdeaIC2020.1
drwxr-xr-x  23 alekseikorshun  staff   736B Nov 12 10:42 IdeaIC2020.2
drwxr-xr-x   4 alekseikorshun  staff   128B Jan 25  2019 PrivacyPolicy
-rw-r--r--   1 alekseikorshun  staff   2.6K Aug 27 19:59 bl
drwxr-xr-x   3 alekseikorshun  staff    96B May  2  2018 consentOptions
-rw-r--r--   1 alekseikorshun  staff   3.7K Apr 13  2018 crl
```

```
ls -dhAl ~/Library/Preferences/*/
drwx------  72 alekseikorshun  staff   2.3K Nov 12 19:28 /Users/alekseikorshun/Library/Preferences/ByHost/
drwxr-xr-x   3 alekseikorshun  staff    96B Nov  1  2019 /Users/alekseikorshun/Library/Preferences/alfred-notifier-nodejs/
drwx------   3 alekseikorshun  staff    96B Mar  8  2017 /Users/alekseikorshun/Library/Preferences/com.apple.LaunchServices/
drwxr-xr-x   3 root            wheel    96B Feb  9  2019 /Users/alekseikorshun/Library/Preferences/com.easeus.datarecoverywizard/
drwx------   3 alekseikorshun  staff    96B Nov  5  2018 /Users/alekseikorshun/Library/Preferences/org.videolan.vlc/
```

**Comment by bchatard** [comment]
please check version 1.4.1

**Comment by AlexeyKorshun** [comment]
@bchatard it works :) thx

**Comment by Glennmen** [comment]
Latest version fixed it! Thanks
