### ISSUE TITLE
idea throw error

### ISSUE THREAD

**Issue by sqmwin** [bchatard/alfred-jetbrains#17]
**Error: Command failed: /bin/sh -c which idea**
    at makeError (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:174:9)
    at module.exports.sync (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:338:15)
    at handleShell (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:117:9)
    at Function.module.exports.shellSync (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:361:43)
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:82:24)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:118:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:15:38)

**Comment by beedaan** [comment]
what was the resolution to this?  I'm using zsh and the workflow can't find the `idea` script

**Comment by bchatard** [comment]
@beedaan Did you create the shell scripts? Did you access to `idea` with your zsh?

**Comment by beedaan** [comment]
I got it to work, but it's not using zsh.  I set the Generate Scripts Location to `/usr/local/bin`.  I picked that location because it's listed in `/etc/paths`.
