### ISSUE TITLE
options.find is not a function

### ISSUE THREAD

**Issue by tldev** [bchatard/alfred-jetbrains#170]
**Describe the bug**
Trying to search my projects with `mine ha..` and presented with error:
```
TypeError: options.find is not a function
    at Object.recentProjects (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:40:43)
    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:66:43)
    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
```

-
JetBrains - Open Project - v3 1.4.0
Alfred 4.1.1
darwin 19.6.0

**To Reproduce**

Not sure how to reproduce. I tried reinstalling the plugin and it still happens. However, it was working for a time.

**Additional context**
I manually renamed the rubymine bin from `rubymine` to `mine` to match the old bin style

**Comment by freekmurze** [comment]
Just upgraded to 1.4.1 and this issue seems to still be present.

**Comment by rymek** [comment]
```
TypeError: options.find is not a function
    at Object.recentProjects (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:40:43)
    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:66:43)
    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
```

-
JetBrains - Open Project - v3 1.4.1
Alfred 4.2.1
darwin 20.2.0

same problem here

**Comment by DieterHolvoet** [comment]
Same issue here, running PhpStorm 2020.3 RC (Build #PS-203.5981.118, built on November 26, 2020).

**Comment by bchatard** [comment]
Please bump to version 1.4.2

**Comment by tldev** [comment]
Thanks @bchatard  - works like a charm

**Comment by freekmurze** [comment]
Thank you so much @bchatard! Works again! 👍

<img width="781" alt="image" src="https://user-images.githubusercontent.com/483853/100920718-cdca4700-34db-11eb-8d27-9aa586bf247f.png">

**Comment by klassm** [comment]
Maybe I am the only one, but for me it still does not work. It is looking better though. However

`option["@_name"] === "additionalInfo";`

won't return anything for me. Object.keys(option) gives me [0,1] - whyever. Maybe it is the node version? 

`
╰─$ node -v
v14.10.0
`

Still looking for a solution ...

**Comment by bchatard** [comment]
@klassm please take a look on 1.4.4

**Comment by klassm** [comment]
Yes that works. Thank you so much @bchatard !
