### ISSUE TITLE
Error: ENOENT: no such file or directory on Intellj IDEA 2020.3

### ISSUE THREAD

**Issue by dailyworker** [bchatard/alfred-jetbrains#187]
| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.4.4_                                |
| OSX Version               | _10.15.7_                              |
| Alfred Version            | _4.3_                                  |
| JetBrains Product/Version | _Intellj IDEA / 2020.3_                    |
| Installation type         | _JB Toolbox_ |
| Node version              | _15.4.0_ (`node --version`)            |
| NPM version               | _7.0.15_ (`npm --version`)              |

**Description**

<img width="569" alt="Screen Shot 2020-12-22 at 6 41 24 PM" src="https://user-images.githubusercontent.com/22961251/102874091-e7efa900-4439-11eb-94fb-7e9d6de5ddd2.png">

I don't know for some reason, but the problem seems to be that the script points to a strange path (like ../Application Support/Google).

**Error log**

```
Error: ENOENT: no such file or directory, scandir '/Users/seansin/Library/Application Support/Google'
    at Proxy.readdirSync (node:fs:1044:3)
    at getDirectories (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:10:6)
    at getPreferencePath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:75:19)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:157:30)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
```

The workflow reinstallation was carried out first.

```sh
$ rm -rf /usr/local/lib/node_modules/@bchatard
$ npm uninstall -g @bchatard/alfred-jetbrains
$ npm install -g @bchatard/alfred-jetbrains
```

After that, we rechecked the generated idea shell script.

<img width="660" alt="Screen Shot 2020-12-22 at 6 43 18 PM" src="https://user-images.githubusercontent.com/22961251/102874263-1ff6ec00-443a-11eb-8617-1cd956b7f677.png">

`cat $(which idea) result`

```sh
#!/bin/sh
#Generated by JetBrains Toolbox 1.19.7784 at 2020-12-22T18:29:04.610887

declare -a ideargs=()
declare -- wait=""

for o in "$@"; do
  if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
    wait="-W"
    o="--wait"
  fi
  if [[ "$o" =~ " " ]]; then
    ideargs+=("\"$o\"")
  else
    ideargs+=("$o")
  fi
done

open -na "/Users/seansin/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.5981.155/IntelliJ IDEA.app/Contents/MacOS/idea" $wait --args "${ideargs[@]}"%
```

How can we resolve this issue?

**Comment by bchatard** [comment]
please check 1.5.0

**Comment by dailyworker** [comment]
@bchatard Updating to version 1.5.0 did not solve the above error.

What's the problem?

**Comment by mathieutu** [comment]
Getting the same error when fresh installing today.

**Comment by bchatard** [comment]
@dailyworker & @mathieutu ok I understand the issue. For some weird reason the check of directory existence throw an exception when searching for the "product information". 
A quick workaround is to alter `src/product.js`, to change the order of the directory list (~ line 61): 
```diff
- `${process.env.HOME}/Library/Application Support/Google`, // >= Android Studio 4.1
- `${process.env.HOME}/Library/Application Support/JetBrains`, // >= 2020.*
+ `${process.env.HOME}/Library/Application Support/JetBrains`, // >= 2020.*
+ `${process.env.HOME}/Library/Application Support/Google`, // >= Android Studio 4.1
```

I will work to a proper fix as soon as I can
