### ISSUE TITLE
Error: Unable to find bin for PhpStorm. Search for bin named: phpstorm, pstorm 

### ISSUE THREAD

**Issue by iArt0s** [bchatard/alfred-jetbrains#205]
Hey, Could you help me fix this?

What I did:
1.$ npm install -g @bchatard/alfred-jetbrains
2.
<img width="440" alt="CleanShot 2021-03-11 at 14 07 04@2x" src="https://user-images.githubusercontent.com/43988287/110778194-1334a800-8273-11eb-9017-df5f83a5a6ed.png">
3. replace this string
<img width="1337" alt="CleanShot 2021-03-11 at 14 07 32@2x" src="https://user-images.githubusercontent.com/43988287/110778265-2fd0e000-8273-11eb-9d2f-3cfc32f4f30b.png">

and it still doesnt work

```
Error: Unable to find bin for PhpStorm. Search for bin named: phpstorm, pstorm
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:116:11)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:158:31)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```

-
JetBrains - Open Project - v3 1.5.0
Alfred 4.3.2
darwin 20.3.0

**Comment by bchatard** [comment]
Shell script config should be like this on Toolbox level
![image](https://user-images.githubusercontent.com/829364/110784953-9dc4d980-826a-11eb-86d7-be85a73c9bf0.png)

Then on product level like this
![image](https://user-images.githubusercontent.com/829364/110785036-baf9a800-826a-11eb-89f9-ade3c8e165c0.png)

I don't get your step 3, what is it?

**Comment by iArt0s** [comment]
yeah,thanks.Works!
