### ISSUE TITLE
Can't find any project 

### ISSUE THREAD

**Issue by Meedly** [bchatard/alfred-jetbrains#215]
IDEA had no response when open project, So i clear my workspace and move IDEA directory to backup

I found i couldn't open any project in alfred bar After i reinstall IDEA and clone project

I try to reinstall workflow but it's not work ,  Which setting can define the 'options' XML path?

Error: Can't find 'options' XML in /Users/xxx/Library/Application Support/JetBrains/IntelliJIdea2021.1-backup
    at Object.getProjectPaths [as get] (/Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)
    at Object.getItems (/Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)
    at /Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/Users/xxx/.nvm/versions/node/v10.21.0/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | v1.5.0                               |
| OSX Version               | 10.15.7                              |
| Alfred Version            | 4.3.4[1229]                                 |
| JetBrains Product/Version | _PhpStorm / 2020.1_                    |
| Installation type         | dmg |
| Node version              | v10.21.0         |
| NPM version               | 6.14.4        |

**Comment by pxlrbt** [comment]
@Meedly Did you solve this? I am having the same issue.
