### ISSUE TITLE
Rider and Goland,can not work

### ISSUE THREAD

**Issue by tomatopunk** [bchatard/alfred-jetbrains#221]
**Check [Troubleshooting](/doc/troubleshooting.md) first**

**Describe the bug**

When searching for the rider item, the item is not displayed, but the `clock`

searching for the goland item,error message:Can't find 'options' XML.

**To Reproduce**

1. Go to 'alfred'
2. Click on 'rider/goland xxxx'
3. Scroll down to 'rider:clock,goland:error'

**Screenshots**

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.5.0_                                |
| OSX Version               | _11.3.1 Macos Big Sur(no arm)                   |
| Alfred Version            | _4.3.4_                                  |
| JetBrains Product/Version | _goland / 2021.1.3_rider/2021.1.3                    |
| Installation type         | JB Toolbox|
| Node version              | _v14.17.1_ (`node --version`)            |
| NPM version               | _6.14.13_ (`npm --version`)              |

**Additional context**

** rider log info **

[10:50:43.192] Logging Started...
[10:50:50.132] JetBrains - Open Project - v3[Script Filter] Queuing argument ''
[10:50:50.920] JetBrains - Open Project - v3[Script Filter] Script with argv '' finished
[10:50:50.921] JetBrains - Open Project - v3[Script Filter] {
	"items": [
		{
			"title": "Retrieve Product: 6ms",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
			}
		},
		{
			"title": "Retrieve Projects: 105ms",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
			}
		}
	]
}
[10:50:53.221] JetBrains - Open Project - v3[Script Filter] Queuing argument 'a'
[10:50:53.466] JetBrains - Open Project - v3[Script Filter] Queuing argument 'ad'
[10:50:53.650] JetBrains - Open Project - v3[Script Filter] Queuing argument 'ada'
[10:50:53.687] JetBrains - Open Project - v3[Script Filter] Script with argv 'a' finished
[10:50:53.691] JetBrains - Open Project - v3[Script Filter] {
	"items": [
		{
			"title": "Match Projects: 2ms",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
			}
		}
	]
}
[10:50:54.103] JetBrains - Open Project - v3[Script Filter] Script with argv 'ada' finished
[10:50:54.107] JetBrains - Open Project - v3[Script Filter] {
	"items": [
		{
			"title": "Match Projects: 2ms",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
			}
		}
	]
}

** goland log info **

[10:50:43.192] Logging Started...
[10:51:47.253] JetBrains - Open Project - v3[Script Filter] Queuing argument ''
[10:51:48.018] JetBrains - Open Project - v3[Script Filter] Script with argv '' finished
[10:51:48.020] ERROR: JetBrains - Open Project - v3[Script Filter] Code 1: {
	"items": [
		{
			"title": "Error: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)\n```\n\n-\nJetBrains - Open Project - v3 1.5.0\nAlfred 4.3.4\ndarwin 20.4.0",
				"largetype": "Error: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
[10:51:48.229] JetBrains - Open Project - v3[Script Filter] Queuing argument 'a'
[10:51:48.548] JetBrains - Open Project - v3[Script Filter] Queuing argument 'ad'
[10:51:48.733] JetBrains - Open Project - v3[Script Filter] Script with argv 'a' finished
[10:51:48.740] ERROR: JetBrains - Open Project - v3[Script Filter] Code 1: {
	"items": [
		{
			"title": "Error: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)\n```\n\n-\nJetBrains - Open Project - v3 1.5.0\nAlfred 4.3.4\ndarwin 20.4.0",
				"largetype": "Error: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
[10:51:48.800] JetBrains - Open Project - v3[Script Filter] Queuing argument 'ada'
[10:51:49.222] JetBrains - Open Project - v3[Script Filter] Script with argv 'ad' finished
[10:51:49.225] ERROR: JetBrains - Open Project - v3[Script Filter] Code 1: {
	"items": [
		{
			"title": "Error: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)\n```\n\n-\nJetBrains - Open Project - v3 1.5.0\nAlfred 4.3.4\ndarwin 20.4.0",
				"largetype": "Error: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
[10:51:49.702] JetBrains - Open Project - v3[Script Filter] Script with argv 'ada' finished
[10:51:49.710] ERROR: JetBrains - Open Project - v3[Script Filter] Code 1: {
	"items": [
		{
			"title": "Error: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)\n```\n\n-\nJetBrains - Open Project - v3 1.5.0\nAlfred 4.3.4\ndarwin 20.4.0",
				"largetype": "Error: Can't find 'options' XML in /Users/murphy/Library/Application Support/JetBrains/GoLand2021.1-backup\n    at Object.getProjectPaths [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:123:9)\n    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:32)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:19:23\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}

**Comment by tomatopunk** [comment]
cat $(which /usr/local/bin/rider)

#!/bin/sh
#Generated by JetBrains Toolbox 1.20.8804 at 2021-06-22T10:56:34.630166

declare -a ideargs=()
declare -- wait=""

for o in "$@"; do
  if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
    wait="-W"
    o="--wait"
  fi
  if [[ "$o" =~ " " ]]; then
    ideargs+=("\"$o\"")
  else
    ideargs+=("$o")
  fi
done

open -na "/Users/murphy/Library/Application Support/JetBrains/Toolbox/apps/Goland/ch-0/211.7442.57/GoLand.app/Contents/MacOS/goland" $wait --args "${ideargs[@]}"

---
cat $(which /usr/local/bin/rider)

#!/bin/sh
#Generated by JetBrains Toolbox 1.20.8804 at 2021-06-22T10:56:34.631588

declare -a ideargs=()
declare -- wait=""

for o in "$@"; do
  if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
    wait="-W"
    o="--wait"
  fi
  if [[ "$o" =~ " " ]]; then
    ideargs+=("\"$o\"")
  else
    ideargs+=("$o")
  fi
done

open -na "/Users/murphy/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/211.7442.29/Rider.app/Contents/MacOS/rider" $wait --args "${ideargs[@]}"
