### ISSUE TITLE
Can't find application path for IntelliJIdea.(2021.1.1)

### ISSUE THREAD

**Issue by CYKin** [bchatard/alfred-jetbrains#239]
Q | A
--- | ---
Workflow version | _1.7.1_
OSX Version | _12.0.1_
Alfred Version | _4.6.1_
JetBrains Product/Version | _IntelliJ IDEA / 2021.1.1_
Installation type | _JB Toolbox_

### Description

![image](https://user-images.githubusercontent.com/25165772/149297637-5a781a4c-c016-4849-9092-58418316b136.png)

~~~
{
    "items":[
        {
            "title":"Error: Can't find application path for IntelliJIdea.",
            "subtitle":"Press ⌘L to see the full error and ⌘C to copy it.",
            "valid":false,
            "text":{
                "copy":"```\nError: Can't find application path for IntelliJIdea.\n    at getApplicationPath (file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/findProduct.js:156:9)\n    at findProduct (file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/findProduct.js:166:31)\n    at file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:16:17\n```\n\n-\nJetBrains - Open Project - v3 1.7.1\nAlfred 4.6.1\ndarwin 21.1.0",
                "largetype":"Error: Can't find application path for IntelliJIdea.\n    at getApplicationPath (file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/findProduct.js:156:9)\n    at findProduct (file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/findProduct.js:166:31)\n    at file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:16:17"
            },
            "icon":{
                "path":"/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
            }
        }
    ]
}
~~~

![image](https://user-images.githubusercontent.com/25165772/149297035-cd119202-c3fa-4419-9e31-17588106d056.png)

![image](https://user-images.githubusercontent.com/25165772/149297070-9b778484-b068-4f32-9f0e-ede310241c66.png)

![image](https://user-images.githubusercontent.com/25165772/149297320-4d3d27d8-a3bc-447e-9fdf-355c21fa53a9.png)

Thanks!

**Comment by t-ober** [comment]
I seem to have the same problem!

**Comment by bchatard** [comment]
hi,

other products have the same issue?
Can you provide the content of `idea` bin?

**Comment by CYKin** [comment]
您发给我的信件已经收到。我将尽快回复。                                                                        -----王昌勇   This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by iamkyu** [comment]
I had the same problem, but it was solved after re-executing toolbox.

**Comment by CYKin** [comment]
您发给我的信件已经收到。我将尽快回复。                                                                        -----王昌勇   This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by HoschiAndre** [comment]
Hello I have the same issue ... but I installed IntelliJ with brew package manager. And I can't find the idea binary.

I looked in:
/local/bin/Caskroom

no idea binary.

**Comment by bchatard** [comment]
Please check the doc: https://github.com/bchatard/alfred-jetbrains#init-shell-script

**Comment by CYKin** [comment]
您发给我的信件已经收到。我将尽快回复。                                                                        -----王昌勇   This is an automatic reply, confirming that your e-mail was received.Thank you
