### ISSUE TITLE
Error: Can't find 'options' XML in....

### ISSUE THREAD

**Issue by ainsleyclark** [bchatard/alfred-jetbrains#240]
Trying to launch GoLand using workflow but recieving error: 

```
Error: Can't find 'options' XML in /Users/me/Library/Application Support/JetBrains/GoLand2021.3-backup
    at getProjectPaths (file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:132:9)
    at getItems (file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:19)
    at file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:21:15
    at async Promise.all (index 0)
```

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Node version              | 17.4.0            |
| NPM version               | 8.3.1             |

**Comment by bchatard** [comment]
Hi,

Just check with latest GoLand release and everything works fine.
Did you have this file: `~/Library/Application\ Support/JetBrains/GoLand2021.3/options/recentProjects.xml` (path need to be adapted to yours)
If yes can you provide the content?

**Comment by ainsleyclark** [comment]
Hi there,

Thanks for your reply.  Yep it exists, content below.

```xml
<application>
  <component name="RecentProjectsManager">
    <option name="additionalInfo">
      <map>
        <entry key="$USER_HOME$/Desktop/Reddico/tools/go-log">
          <value>
            <RecentProjectMetaInfo frameTitle="go-log – ~/go-log/formatter.go" projectWorkspaceId="2130JNvPACKXjCB3b4AeIGn9MPE">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="GO-212.4746.93" />
              <option name="buildTimestamp" value="1627368339106" />
              <frame x="0" y="25" width="3008" height="1667" extendedState="6" />
              <option name="productionCode" value="GO" />
              <option name="projectOpenTimestamp" value="1637154390458" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
        <entry key="$USER_HOME$/apis/go-mail">
          <value>
            <RecentProjectMetaInfo frameTitle="go-mail" projectWorkspaceId="1qnwcKFwm6DQeZT0XRPPFYMFM9J">
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="GO-212.4746.93" />
              <option name="buildTimestamp" value="1627368304537" />
              <frame x="-3008" y="25" width="3008" height="1667" extendedState="6" />
              <option name="productionCode" value="GO" />
              <option name="projectOpenTimestamp" value="1640867671540" />
            </RecentProjectMetaInfo>
          </value>
      </map>
    </option>
    <option name="lastProjectLocation" value="$USER_HOME$/Desktop" />
  </component>
</application>%

**Comment by bchatard** [comment]
where this file is located?

**Comment by ainsleyclark** [comment]
~/Library/Application\ Support/JetBrains/GoLand2021.3/options/recentProjects.xml

**Comment by bchatard** [comment]
on your first message the path was `/Users/me/Library/Application Support/JetBrains/GoLand2021.3-backup`

can you check this path too?

**Comment by ainsleyclark** [comment]
Apologies, yes I can see that it's trying to use `GoLand2021.3-backup` instead of `GoLand2021.3`.
Would removing `GoLand2021.3-backup` fix this?

**Comment by mohamed-haidara-cko** [comment]
I had the same issue. You can safely delete the `-backup` folder and clean the project cache with the action `jb clean` in Alfred. 

It seems that the workflow is not reading the correct folder here.

**Comment by ainsleyclark** [comment]
Thank you @mohamed-haidara-cko that worked like a treat.
