### ISSUE TITLE
Using Rider and getting error: TypeError: options.find is not a function

### ISSUE THREAD

**Issue by khoanl** [bchatard/alfred-jetbrains#274]
Hi, 
I tried to install the plugin on MacOS 12.4 with node LTS 14 and LTS 16 with NVM.
For some reason when I try to use "rider " in Alfred 4, I get the following error.

Error from Alfred Debug window:
```
[12:13:44.622] Logging Started...
[12:13:47.400] JetBrains - Open Project - v3[[Script Filter](alfredpreferences:workflows%3Eworkflow%3E@bchatard-alfred-jetbrains%3E9A5C474B-A56F-4C12-9723-079CD543C502)] Queuing argument ''
[12:13:47.636] JetBrains - Open Project - v3[[Script Filter](alfredpreferences:workflows%3Eworkflow%3E@bchatard-alfred-jetbrains%3E9A5C474B-A56F-4C12-9723-079CD543C502)] Script with argv '' finished
[12:13:47.641] JetBrains - Open Project - v3[[Script Filter](alfredpreferences:workflows%3Eworkflow%3E@bchatard-alfred-jetbrains%3E9A5C474B-A56F-4C12-9723-079CD543C502)] {
	"items": [
		{
			"title": "TypeError: options.find is not a function",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nTypeError: options.find is not a function\n    at Object.recentSolutions (file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:82:43)\n    at getProjectPaths (file:///Users/khoa/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:103:43)\n    at getItems (file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:19)\n    at file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:21:15\n    at async Promise.all (index 0)\n```\n\n-\nJetBrains - Open Project - v3 1.9.2\nAlfred 4.6.6\ndarwin 21.5.0",
				"largetype": "TypeError: options.find is not a function\n    at Object.recentSolutions (file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:82:43)\n    at getProjectPaths (file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:103:43)\n    at getItems (file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:19)\n    at file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:21:15\n    at async Promise.all (index 0)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

Error from the Alfred spotlight with cmd + c:

```
TypeError: options.find is not a function
    at Object.recentSolutions (file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:82:43)
    at getProjectPaths (file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:103:43)
    at getItems (file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:19)
    at file:///Users/xxxx/.nvm/versions/node/v16.13.0/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:21:15
    at async Promise.all (index 0)
```

-
JetBrains - Open Project - v3 1.9.2
Alfred 4.6.6
darwin 21.5.0

**Comment by tomstolarczuk** [comment]
@bchatard do you accept PRs?

**Comment by bchatard** [comment]
yes

**Comment by khoanl** [comment]
@tomstolarczuk Did you manage to fix this and get it working? :D

**Comment by tomstolarczuk** [comment]
@khoanl yes, it's quite easy. recent rider solutions file has now the same structure as recent projects files in case of other apps (eg. webstorm)

**Comment by khoanl** [comment]
@tomstolarczuk did you manage to test it after this fix if everything works? To me it seems to get rid of the error, but nothing happens when I try to use the command?
