### ISSUE TITLE
pstorm looks to be deprecated in new EAP

### ISSUE THREAD

**Issue by PhilETaylor** [bchatard/alfred-jetbrains#310]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

in phpStorm 2023.1 EAP (without toolbox) it looks like the command line launcher `pstorm` is no longer a thing

### To Reproduce

When you go to Tools -> Create Command Line Launcher you get: 

<img width="560" alt="ScreenShot-2023-03-01-20 49 28" src="https://user-images.githubusercontent.com/400092/222261793-8b5edfce-eef6-45cc-975e-1a0803e8ab86.png">

The link for `online help` goes to https://www.jetbrains.com/help/phpstorm/working-with-the-ide-features-from-command-line.html

I have added the following in my .zshrc (but including the whole .zshrc slows things down anyway https://github.com/bchatard/alfred-jetbrains/issues/271)

```
export PATH="/Applications/PhpStorm 2023.1 EAP.app/Contents/MacOS:$PATH"
```

### Expected behavior

Alfred can no longer find phpStorm to launch

### Alfred Version

5.06[2110]

### Node Version

19.7.0

### NPM Version

9.5.1

### Jetbrains Product & Version

phpStorm 2023.1 EAP

### Installation type

Classic via .dmg

### OS

macOS 13.3 Beta 2

**Comment by bchatard** [comment]
I bump all available IDE to 2023.1 and no visible change.
here with WebStorm (since PhpStorm is not yet available in 2023.1)
<img width="547" alt="image" src="https://user-images.githubusercontent.com/829364/229753045-52f895df-7204-4206-aae8-783750203028.png">


I use JetBrains Toolbox, configured like this
<img width="433" alt="image" src="https://user-images.githubusercontent.com/829364/229753363-1cf9ca78-fe1c-450f-b456-062a87c2b1e4.png">

default settings when I install Toolbox few years ago (yes I haven't refresh my laptop since a while)

**Comment by bchatard** [comment]
Oups sorry

Can you try to echo your $PATH in Alfred script filter?

**Comment by PhilETaylor** [comment]
```
Error: Can't find application path for PhpStorm.
    at getApplicationPath (file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/findProduct.js:165:9)
    at findProduct (file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/findProduct.js:175:31)
    at file:///opt/homebrew/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:16:17
```

-
JetBrains - Open Project - v3 1.9.8
Alfred 5.1
darwin 22.5.0

**Comment by PhilETaylor** [comment]
```
$ which phpstorm
/Applications/PhpStorm 2023.1 EAP.app/Contents/MacOS/phpstorm
```

**Comment by bchatard** [comment]
Can you switch to regular version (EAP support is not "official")?
And put the content of `phpstorm`?

**Comment by PhilETaylor** [comment]
I also have/had the standard regular version installed too 

also note my default shell is zsh and not bash - no idea if that is an issue

```
 0 drwxr-xr-x@  3 phil     96 Apr  4 12:00 PhpStorm 2023.1 EAP.app
 0 drwxr-xr-x@  3 phil     96 Mar 29 22:03 PhpStorm.app
```
<img width="1131" alt="ScreenShot-2023-04-05-11 17 20" src="https://user-images.githubusercontent.com/400092/230052452-ba75c6e6-b9d7-44c4-8f70-9de03d98effb.png">

**Comment by PhilETaylor** [comment]
so a few other points

1. I had an old /usr/local/bin/phpstorm - I have now deleted this
2. debugging, I see that you are trying to look at the binary content of the phpstorm file and match a regex, this returns false for the toolbox and non toolbox case 

If I change the RegExp for the non ToolBox case to `JetBrains` like

```
 // non Toolbox case
  const oldPattern = new RegExp("JetBrains");
  const oldMatch = oldPattern.exec(binContent);
  if (oldMatch && oldMatch.length === 1) {
    return oldMatch[1];
  }
```

THEN IT WORKS!!!

This is because `phpstorm` file is now a binary, and there is limited text in it - example:
<img width="1305" alt="ScreenShot-2023-04-05-11 33 28" src="https://user-images.githubusercontent.com/400092/230056178-812de21d-d9f7-454c-87df-cb6c7552e743.png">

**Comment by PhilETaylor** [comment]
I have no idea what's going on now. I have reinstalled from scratch and your original code works. hmm.....

**Comment by PhilETaylor** [comment]
ok ignore everything I said. It doesn't work. :( I need sleep and I'll try again

**Comment by bchatard** [comment]
I have this, a helper script available globally 
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/829364/230294432-f6bbc7e0-3fd2-4f1a-8168-a92ce8ab1525.png">

which contains link to "real bin"
<img width="935" alt="image" src="https://user-images.githubusercontent.com/829364/230294785-86f06a68-c6e6-4592-8204-b78a97f057ac.png">


I'm really curious about all this change...

**Comment by PhilETaylor** [comment]
That script appears to be "generated by toolbox"

Im not using toolbox to install/manage my phpStorm (why would anyone, its just overkill, uses resources that are not needed constantly running in the background)

**Comment by bchatard** [comment]
But did you generate script as mentioned in documentation?

**Comment by bchatard** [comment]
Ok, so for now I have no clean solution. Your solution works fine? Can you create a PR?

I'm currently working on a v2 which should fix this kind of issue

**Comment by PhilETaylor** [comment]
my solution works to launch phpStorm if its not yet open, but it cannot be used to switch projects if phpStorm is already open as the new binary just hangs until you close phpstorm, and once closed Alfred is then able to reopen it, meaning you cannot invoke phpStorm twice using your workflow, making the workflow pretty useless (Although, I rarely use your workflow now, as the new phpStorm UI has a great project switcher with cmd+o to launch the Recent Projects dialog

**Comment by bchatard** [comment]
Ok, maybe some additional parameters are needed to execute the process in background properly (like in toolbox script)

**Comment by bchatard** [comment]
I re-read the doc you mentioned in first comment, I will use open command from macOS to start ide

**Comment by sangkyu-kim** [comment]
My Intellij IDEA 2023.1 (New versions), got seems to be same issue.

**Comment by bchatard** [comment]
Hi,

If you are adventurous, you can try the v2 pre-release.
Be careful, it's a pre-release, tested on Intel mac

Can be installed like this: `npm install -g @bchatard/alfred-jetbrains@next` 

This should fix issue with 2023 version (tested with PyCharm, installed from dmg)

**Comment by PhilETaylor** [comment]
Absolutely flawless! (After I downgraded from EAP to Stable phpStorm) 

🚀 Thanks! 

Sign up for GitHub Sponsors, https://github.com/sponsors or add a donation/buy now button :)

**Comment by bchatard** [comment]
thanks for your feedback!

if you have time to send me (via an other issue), more feedback (speedier, search more accurate, macos version/chip etc) I really love it
