### ISSUE TITLE
[Alfred 5]Can't find application path for IntelliJIdea

### ISSUE THREAD

**Issue by tguitars** [bchatard/alfred-jetbrains#322]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug
```
Error: Can't find application path for IntelliJIdea.
    at getApplicationPath (file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/findProduct.js:165:9)
    at findProduct (file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/findProduct.js:175:31)
    at file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:16:17
```

-
JetBrains - Open Project - v3 1.9.8
Alfred 5.1
darwin 21.6.0

### To Reproduce

- Install latest Alfred 
- Run `npm install -g @bchatard/alfred-jetbrains`
- Open Alfred, type `idea` 

btw,  command line launcher is changed. 

```
To make the IDE accessible from the command line, please add '/Applications/IntelliJ IDEA.app/Contents/MacOS' to the $PATH variable and use 'idea' to run commands.  Please see the online help for more details.
```

### Expected behavior

No error above, the project list would be shown up

### Alfred Version

5.1.2134

### Node Version

v20.0.0

### NPM Version

9.6.4

### Jetbrains Product & Version

intelliJIdeaUltimate & IntelliJ IDEA 2023.1.1

### Installation type

Classic via .dmg

### OS

macOS 12.3

**Comment by juarinu** [comment]
In my case (IntelliJ CE), I changed the product designation to `intelliJIdeaCommunity` in the script and make a link to the app (`ln -s "/Applications/IntelliJ IDEA CE.app" "~/Applications/IntelliJ IDEA Community Edition.app"`) to solve this issue.

**Comment by bchatard** [comment]
@juarinu please raise another issue, since this one is for v1

**Comment by tguitars** [comment]
@bchatard 

still seeing the error, but it's different one.  btw, I'm using "IntelliJ IDEA Ultimate"

```
06:57:21.197] Logging Started...
[06:57:26.875] JetBrains - Open Project[Script Filter] Queuing argument '(null)'
[06:57:26.928] JetBrains - Open Project[Script Filter] Script with argv '(null)' finished
[06:57:26.930] JetBrains - Open Project[Script Filter] {
  "items": [
    {
      "uid": "Can't find settings path for IntelliJIdeaCommunity",
      "title": "Can't find settings path for IntelliJIdeaCommunity",
      "match": "Can't find settings path for IntelliJIdeaCommunity Preferences]",
      "subtitle": "Please check if preferences 'IdeaIC' exists in [~/Library/Application Support/Google, ~/Library/Application Support/JetBrains, ~/Library/Preferences]",
      "arg": "Please check if preferences 'IdeaIC' exists in [~/Library/Application Support/Google, ~/Library/Application Support/JetBrains, ~/Library/Preferences]",
      "autocomplete": "Can't find settings path for IntelliJIdeaCommunity",
      "text": {
        "copy": "Please check if preferences 'IdeaIC' exists in [~/Library/Application Support/Google, ~/Library/Application Support/JetBrains, ~/Library/Preferences]",
        "largetype": "Can't find settings path for IntelliJIdeaCommunity"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    },
    {
      "uid": "Debug: CLI version 0.0.9",
      "title": "Debug: CLI version 0.0.9",
      "match": "Debug: CLI version 0.0.9 0.0.9",
      "subtitle": "0.0.9",
      "arg": "0.0.9",
      "autocomplete": "Debug: CLI version 0.0.9",
      "text": {
        "copy": "0.0.9",
        "largetype": "Debug: CLI version 0.0.9"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertNoteIcon.icns"
      }
    },
    {
      "uid": "Debug: Log alfred_jetbrains_cli_2023-05-09.log",
      "title": "Debug: Log alfred_jetbrains_cli_2023-05-09.log",
      "match": "Debug: Log alfred_jetbrains_cli_2023-05-09.log alfred_jetbrains_cli_2023-05-09.log",
      "subtitle": "/var/folders/r9/ch_c4nps2bv2lwbhybj156w40000gr/T/alfred_jetbrains_cli_2023-05-09.log",
      "arg": "/var/folders/r9/ch_c4nps2bv2lwbhybj156w40000gr/T/alfred_jetbrains_cli_2023-05-09.log",
      "autocomplete": "Debug: Log alfred_jetbrains_cli_2023-05-09.log",
      "text": {
        "copy": "/var/folders/r9/ch_c4nps2bv2lwbhybj156w40000gr/T/alfred_jetbrains_cli_2023-05-09.log",
        "largetype": "Debug: Log alfred_jetbrains_cli_2023-05-09.log"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ProblemReport.icns"
      }
    },
    {
      "uid": "Debug: Took 3ms",
      "title": "Debug: Took 3ms",
      "match": "Debug: Took 3ms Started at: 2023-05-09T06:57:26.918484 || Ended at: 2023-05-09T06:57:26.922367",
      "subtitle": "Started at: 2023-05-09T06:57:26.918484 || Ended at: 2023-05-09T06:57:26.922367",
      "arg": "Started at: 2023-05-09T06:57:26.918484 || Ended at: 2023-05-09T06:57:26.922367",
      "autocomplete": "Debug: Took 3ms",
      "text": {
        "copy": "Started at: 2023-05-09T06:57:26.918484 || Ended at: 2023-05-09T06:57:26.922367",
        "largetype": "Debug: Took 3ms"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
      }
    }
  ]
}
```

**Comment by tguitars** [comment]
```
~ ❯ ls /usr/local/bin/idea
/usr/local/bin/idea
~ ❯ ls "/Applications/IntelliJ IDEA.app/Contents/MacOS"
idea

```

**Comment by bchatard** [comment]
Please check the documentation about customization

**Comment by tguitars** [comment]
I have changed the product Edition to `Ultimate`. is there anything else I need to change?

**Comment by bchatard** [comment]
Is it working?

**Comment by tguitars** [comment]
No, the error like I posted above

**Comment by bchatard** [comment]
Please open another issue, this one is on v1.
Check your configuration again
