### ISSUE TITLE
Not Available with Apple M3 MAX Chip CPU

### ISSUE THREAD

**Issue by wannte** [bchatard/alfred-jetbrains#341]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.
- [X] Yes, I reload my Alfred cache (with `reload`)

### Describe the bug

`npm install -g @bchatard/alfred-jetbrains` not available in Apple M3 MAX Chip.

log
```
0 verbose cli /Users/wannte/.nvm/versions/node/v22.9.0/bin/node /Users/wannte/.nvm/versions/node/v22.9.0/bin/npm
1 info using npm@10.8.3
2 info using node@v22.9.0
3 silly config load:file:/Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/wannte/.npmrc
5 silly config load:file:/Users/wannte/.nvm/versions/node/v22.9.0/etc/npmrc
6 verbose title npm install @bchatard/alfred-jetbrains
7 verbose argv "install" "--global" "@bchatard/alfred-jetbrains"
8 verbose logfile logs-max:10 dir:/Users/wannte/.npm/_logs/2024-09-28T04_59_28_888Z-
9 verbose logfile /Users/wannte/.npm/_logs/2024-09-28T04_59_28_888Z-debug-0.log
10 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
11 silly logfile done cleaning log files
12 silly idealTree buildDeps
13 silly fetch manifest @bchatard/alfred-jetbrains@*
14 silly packumentCache full:https://registry.npmjs.org/@bchatard%2falfred-jetbrains cache-miss
15 http fetch GET 200 https://registry.npmjs.org/@bchatard%2falfred-jetbrains 1287ms (cache revalidated)
16 silly packumentCache full:https://registry.npmjs.org/@bchatard%2falfred-jetbrains set size:171096 disposed:false
17 silly placeDep ROOT @bchatard/alfred-jetbrains@2.1.1 OK for:  want: *
18 silly reify moves {}
19 info run @bchatard/alfred-jetbrains@2.1.1 postinstall node_modules/@bchatard/alfred-jetbrains ./bin/alfred_jetbrains_cli install
20 info run @bchatard/alfred-jetbrains@2.1.1 postinstall { code: 126, signal: null }
21 verbose stack Error: command failed
21 verbose stack     at promiseSpawn (/Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
21 verbose stack     at spawnWithShell (/Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
21 verbose stack     at promiseSpawn (/Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
21 verbose stack     at runScriptPkg (/Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
21 verbose stack     at runScript (/Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
21 verbose stack     at /Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
21 verbose stack     at run (/Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
21 verbose stack     at /Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
21 verbose stack     at new Promise (<anonymous>)
21 verbose stack     at callLimit (/Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
22 verbose pkgid @bchatard/alfred-jetbrains@2.1.1
23 error code 126
24 error path /Users/wannte/.nvm/versions/node/v22.9.0/lib/node_modules/@bchatard/alfred-jetbrains
25 error command failed
26 error command sh -c ./bin/alfred_jetbrains_cli install
27 error sh: ./bin/alfred_jetbrains_cli: Bad CPU type in executable
28 silly unfinished npm timer reify 1727499569021
29 silly unfinished npm timer reify:build 1727499570378
30 silly unfinished npm timer build 1727499570378
31 silly unfinished npm timer build:deps 1727499570378
32 silly unfinished npm timer build:run:postinstall 1727499570379
33 silly unfinished npm timer build:run:postinstall:node_modules/@bchatard/alfred-jetbrains 1727499570379
34 verbose cwd /Users/wannte
35 verbose os Darwin 23.4.0
36 verbose node v22.9.0
37 verbose npm  v10.8.3
38 verbose exit 126
39 verbose code 126
40 error A complete log of this run can be found in: /Users/wannte/.npm/_logs/2024-09-28T04_59_28_888Z-debug-0.log
```

### To Reproduce

`npm install -g @bchatard/alfred-jetbrains` on Apple M3 MAX Chip

### Alfred Version

5.5

### Workflow Version

2.1.1

### Node Version

v22.9.0

### NPM Version

10.8.3

### Jetbrains Product & Version

intellij 2024.2.1

### Installation type

Classic via .dmg

### OS

macOS 13.3

**Comment by bchatard** [comment]
Hi,

Since I do not have an M3 Max, I can't test it. 

It works on an Intel i9 and M1 Max.

As far as I know there is no issue when compiling dart binary for macOS.

Try to install Rosetta first, maybe it will fix the issue

**Comment by wannte** [comment]
Thanks, recently I installed Rosetta for other application.

When I retry download, now it installed well! You can close issue :)
