### ISSUE TITLE
Error: Command failed: /bin/sh -c which phpstorm

### ISSUE THREAD

**Issue by terryupton** [bchatard/alfred-jetbrains#58]
**Describe the bug**
Cannot load or find PHPstorm projects. Get the following error:

```
Error: Command failed: /bin/sh -c which phpstorm
    at makeError (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:174:9)
    at module.exports.sync (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:338:15)
    at handleShell (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:117:9)
    at Function.module.exports.shellSync (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:361:43)
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:82:24)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:118:31)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:15:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:61:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
```

JetBrains - Open Project - v3 1.1.0
Alfred 4.0.3
darwin 18.7.0
phpstorm 2019.2

I had created the command line launched in PHP as follows:
`/usr/local/bin/pstorm`

**Comment by bchatard** [comment]
version 1.1.1 should fix the issue
