### ISSUE TITLE
EAP build support

### ISSUE THREAD

**Issue by kalbert312** [bchatard/alfred-jetbrains#61]
I like to test out EAP builds for the IDEs from time to time. I'm not sure if there's a seamless way to do this but here's an example:

I'm using the release build of WebStorm and `wstorm ...` works perfectly. When I install the next version of EAP alongside the release build, using `wstorm` will open the release build which is what I would expect.

Is there a recommended way to do this?

Side note: I noticed when JetBrains toolbox installs the EAP, I believe it automatically assigned the name `webstorm1` to the EAP shell script.

**Comment by THPubs** [comment]
Just installed WebStorm EAP and looks like I also face the same issue. The full error I'm getting is:

```
Error: Can't find preference path for WebStorm
    at getPreferencePath (/Users/pubudu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/product.js:81:9)
    at Object.get (/Users/pubudu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/product.js:138:30)
    at /Users/pubudu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/Users/pubudu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/Users/pubudu/.config/yarn/global/node_modules/esm/esm.js:1:251206)
    at /Users/pubudu/.config/yarn/global/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/Users/pubudu/.config/yarn/global/node_modules/esm/esm.js:1:245412)
    at kl (/Users/pubudu/.config/yarn/global/node_modules/esm/esm.js:1:247659)
    at Object.u (/Users/pubudu/.config/yarn/global/node_modules/esm/esm.js:1:287740)
```

**Comment by bchatard** [comment]
hi,

actually there is no plan to support Sable + EAP out of the box:
1. reason 1: the shell script name related to EAP is not "standard" so I can't rely on it (or you have to configure it)
2. reason 2: I need to create (duplicate) existing "script filter" to create EAP variants with another keyword (eg: `eappstorm` will open PhpStorm EAP and `pstorm` will open Stable), which will quit difficult to maintain 

Since I'm quite busy actually, I can't handle this use case, but maybe some PR can help? :)
