### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mathieutu** [bchatard/alfred-jetbrains#8]
Q | A
--- | ---
Workflow version | _1.0.3_
OSX Version | _17.7.0_
Alfred Version | _3.8.1_
JetBrains Product/Version | _PhpStorm / 2019.1_
Installation type | _JB Toolbox_

### Description

I can confirm that there is no .idea folder in this project, though for me it should not raise an error.

```
Error: ENOENT: no such file or directory, scandir '/Users/mathieutu/Projects/particip/.idea'
    at getFiles (/Users/mathieutu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/project/name.js:4:32)
    at Object.viaIml (/Users/mathieutu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/project/name.js:20:24)
    at Object.getProductName [as get] (/Users/mathieutu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/project/name.js:28:43)
    at buildItem (/Users/mathieutu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/project.js:7:28)
    at paths.forEach.path (/Users/mathieutu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/project.js:40:20)
    at Array.forEach (<anonymous>)
    at Object.getItems (/Users/mathieutu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/project.js:39:11)
    at Object.<anonymous> (/Users/mathieutu/.config/yarn/global/node_modules/@bchatard/alfred-jetbrains/src/index.js:12:23)
```

-
JetBrains - Open Project - v3 undefined
Alfred 3.8.1
darwin x64 17.7.0

**Comment by mathieutu** [comment]
I've created the demanded folder, and have the same error from the main folder (my `projects` one) which is not a jetbrain project. (not in the toolbox list)

**Comment by bchatard** [comment]
weird, there is "project folder" without `.idea` folder...
Did you removed `.idea` folder and then trying to re-open it?
Can you provide the following file: `~/Library/Preferences/PhpStorm2019.1/options/recentProjectDirectories.xml` (remove any sensitive data before)

**Comment by mathieutu** [comment]
Indeed, Theses folders are in the list, I think I opened them once by error, or to edit one file.
Maybe a check on the existence of the folder and a filter could do the job?

**Comment by bchatard** [comment]
@mathieutu please take a look on version [1.0.4](https://github.com/bchatard/alfred-jetbrains/releases/tag/v1.0.4)

**Comment by mathieutu** [comment]
Thanks!
It works now.
