### ISSUE TITLE
Can't find preference path for PhpStorm

### ISSUE THREAD

**Issue by jerryklimcik** [bchatard/alfred-jetbrains#86]
**Describe the bug**
I'm getting this error:
```
Error: Can't find preference path for PhpStorm
    at getPreferencePath (/Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:81:9)
    at Object.get (/Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:138:30)
    at /Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:59:3)
    at Object.<anonymous> (/Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/Users/klimcik/‘~/.npm-global’/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```

**To Reproduce**
1.  installation via npm install -g @bchatard/alfred-jetbrains
2. in PhpStorm in "Create Lancher Script" I confirmed path `/usr/local/bin/pstorm` and overwrite an existing file 
3. invoke Alfred
4. type pstorm

Q | A
--- | ---
Workflow version | _1.2.0_
OSX Version | _10.15.1_
Alfred Version | _4.0.6_
JetBrains Product/Version | _PhpStorm / 2019.2.5_
Installation type | _classic .dmg_
Node version | _10.15.3_
NPM version | _6.4.1_

**Additional context**
Maybe I need to create something or I moved something somewhere else but I don't know what is wrong.

**Comment by bchatard** [comment]
hi @jerryklimcik 

can you provide the content of `/usr/local/bin/pstorm`?
did you have a folder named like this: `~/Library/Preferences/PhpStorm*`

**Comment by jerryklimcik** [comment]
hi @bchatard 

content of pstorm:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import socket
import struct
import sys
import traceback

# see com.intellij.idea.SocketLock for the server side of this interface

RUN_PATH = u'/Applications/PhpStorm.app'
CONFIG_PATH = u'/Users/klimcik/Library/Preferences/PhpStorm2019.2'
SYSTEM_PATH = u'/Users/klimcik/Library/Caches/PhpStorm2019.2'


def print_usage(cmd):
    print(('Usage:\n' +
           '  {0} -h | -? | --help\n' +
           '  {0} [project_dir] [-w|--wait]\n' +
           '  {0} [-l|--line line] [project_dir|--temp-project] [-w|--wait] file[:line]\n' +
           '  {0} diff <left> <right>\n' +
           '  {0} merge <local> <remote> [base] <merged>').format(cmd))


def write_to_sock(sock, str):
    if sys.version_info[0] >= 3: str = str.encode('utf-8')
    sock.send(struct.pack('>h', len(str)) + str)


def read_from_sock(sock):
    len = struct.unpack('>h', sock.recv(2))[0]
    return sock.recv(len).decode('utf-8')
```

and I have this folders in `~/Library/Preferences/`
```
lrwxr-xr-x    1 klimcik staff   77 Nov 16 18:42  PhpStorm2018.2 -> '/Users/klimcik/Desktop/Google drive/Mackup/Library/Preferences/PhpStorm2018.2'/
lrwxr-xr-x    1 klimcik staff   77 Nov 16 18:42  PhpStorm2018.3 -> '/Users/klimcik/Desktop/Google drive/Mackup/Library/Preferences/PhpStorm2018.3'/
lrwxr-xr-x    1 klimcik staff   77 Nov 16 18:42  PhpStorm2019.1 -> '/Users/klimcik/Desktop/Google drive/Mackup/Library/Preferences/PhpStorm2019.1'/
lrwxr-xr-x    1 klimcik staff   77 Nov 16 18:42  PhpStorm2019.2 -> '/Users/klimcik/Desktop/Google drive/Mackup/Library/Preferences/PhpStorm2019.2'/
```

Can be something with symlink using Mackup?

**Comment by bchatard** [comment]
Maybe related to symlink. Can you try the following in node REPL?
```shell
$ node
Welcome to Node.js ...
> require('fs').readdirSync(`${process.env.HOME}/Library/Preferences`).filter(path => new RegExp(`PhpStorm(([\\d]{1}|[\\d]{4})\\.[\\d]{1})`).test(path))
```

**Comment by jerryklimcik** [comment]
Here is a result:
```
$ node
> require('fs').readdirSync(`${process.env.HOME}/Library/Preferences`).filter(path => new RegExp(`PhpStorm(([\\d]{1}|[\\d]{4})\\.[\\d]{1})`).test(path))
[ 'PhpStorm2018.2',
  'PhpStorm2018.3',
  'PhpStorm2019.1',
  'PhpStorm2019.2' ]
>
```

**Comment by bchatard** [comment]
hi,

Is it possible to not use the symlink for testing purpose?

**Comment by jerryklimcik** [comment]
Hi, I'm closing this thread. Problem is related to mackup application. I had to return mac to factory settings and I tried it with and without mackup and for some reason it does not work with mackup. It is not such a big deal to live without mackup so I will not deal with it anymore. But thank you for your time and of course for this amazing workflow!
