### ISSUE TITLE
Intellij: TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Stvad** [bchatard/alfred-jetbrains#9]
Q | A
--- | ---
Workflow version | _1.0.3_
OSX Version | _10.14.4_
Alfred Version | _3.8.1_
JetBrains Product/Version | _Intellij / 2019.1_
Installation type |  Caskroom 

### Description
When I try to use workflow with Idea, I get the following error:
```
TypeError: Cannot read property 'length' of null
    at getApplicationPath (/Users/sitalov/.nvm/versions/node/v11.1.0/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:56:13)
    at Object.get (/Users/sitalov/.nvm/versions/node/v11.1.0/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:73:31)
    at Object.<anonymous> (/Users/sitalov/.nvm/versions/node/v11.1.0/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:6:38)
```

As requested, the result of: `cat $(which idea)`:

```
sitalov/workspace  cat $(which idea)
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import socket
import struct
import sys
import os
import time

# see com.intellij.idea.SocketLock for the server side of this interface

RUN_PATH = u'/Applications/IntelliJ IDEA.app'
CONFIG_PATH = u'/Users/sitalov/Library/Preferences/IntelliJIdea2019.1'
SYSTEM_PATH = u'/Users/sitalov/Library/Caches/IntelliJIdea2019.1'


def print_usage(cmd):
    print(('Usage:\n' +
           '  {0} -h | -? | --help\n' +
           '  {0} [project_dir]\n' +
           '  {0} [-l|--line line] [project_dir|--temp-project] file[:line]\n' +
           '  {0} diff <left> <right>\n' +
           '  {0} merge <local> <remote> [base] <merged>').format(cmd))


def process_args(argv):
    args = []

    skip_next = False
    for i, arg in enumerate(argv[1:]):
        if arg == '-h' or arg == '-?' or arg == '--help':
            print_usage(argv[0])
            exit(0)
        elif i == 0 and (arg == 'diff' or arg == 'merge' or arg == '--temp-project'):
            args.append(arg)
        elif arg == '-l' or arg == '--line':
            args.append(arg)
            skip_next = True
        elif skip_next:
            args.append(arg)
            skip_next = False
        else:
            path = arg
            if ':' in arg:
                file_path, line_number = arg.rsplit(':', 1)
                if line_number.isdigit():
                    args.append('-l')
                    args.append(line_number)
                    path = file_path
            args.append(os.path.abspath(path))

    return args


def try_activate_instance(args):
    port_path = os.path.join(CONFIG_PATH, 'port')
    token_path = os.path.join(SYSTEM_PATH, 'token')
    if not (os.path.exists(port_path) and os.path.exists(token_path)):
        return False

    try:
        with open(port_path) as pf:
            port = int(pf.read())
        with open(token_path) as tf:
            token = tf.read()
    except (ValueError):
        return False

    s = socket.socket()
    s.settimeout(0.3)
    try:
        s.connect(('127.0.0.1', port))
    except (socket.error, IOError):
        return False

    found = False
    while True:
        try:
            path_len = struct.unpack('>h', s.recv(2))[0]
            path = s.recv(path_len).decode('utf-8')
            if os.path.abspath(path) == os.path.abspath(CONFIG_PATH):
                found = True
                break
        except (socket.error, IOError):
            return False

    if found:
        cmd = 'activate ' + token + '\0' + os.getcwd() + '\0' + '\0'.join(args)
        if sys.version_info[0] >= 3: cmd = cmd.encode('utf-8')
        encoded = struct.pack('>h', len(cmd)) + cmd
        s.send(encoded)
        time.sleep(0.5)  # don't close the socket immediately
        return True

    return False


def start_new_instance(args):
    if sys.platform == 'darwin':
        if len(args) > 0:
            args.insert(0, '--args')
        os.execvp('/usr/bin/open', ['-a', RUN_PATH] + args)
    else:
        bin_file = os.path.split(RUN_PATH)[1]
        os.execv(RUN_PATH, [bin_file] + args)


ide_args = process_args(sys.argv)
if not try_activate_instance(ide_args):
    start_new_instance(ide_args)
```

**Comment by bchatard** [comment]
@Stvad 
thanks for this information!

please take a look on version [1.0.4](https://github.com/bchatard/alfred-jetbrains/releases/tag/v1.0.4)

**Comment by Stvad** [comment]
@bchatard Thank you! it works now! 🙂
