### ISSUE TITLE
Can't start/use PyCharm Professional

### ISSUE THREAD

**Issue by netgitdom** [bchatard/alfred-jetbrains#92]
**Describe the bug**
I created the shell scripts via the JetBrains Toolbox on my OneDrive. It looks like this

```
#!/bin/sh
# Generated by JetBrains Toolbox 1.16.6067 at Sun Dec 1 08:43:06 2019

open -a "/Users/XXXXXX/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.7142.56/PyCharm.app/Contents/MacOS/pycharm" "$@"

```
I left the products.json unchanged:
  "PyCharm": {
    "preferences": "PyCharm",
    "bin": ["pycharm", "charm"]
  },

If I try to open my projects via Alfred, I´ll get this error message:

Error: Unable to find bin for PyCharm. Search for bin named: pycharm, charm
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:99:11)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:139:31)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:59:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)

**Expected behavior**
I expect my PyCharm Projects

Q | A
--- | ---
Workflow version |  1.2.0
OSX Version | 10.14.6
Alfred Version | 4.0.6
JetBrains Product/Version | PyCharm Professional / 2019.2.5
Installation type JB Toolbox
Node version | v12.11.1
NPM version | 6.11.3

**Additional context**
Same for Data Grip

**Comment by bchatard** [comment]
hi @netgitdom ,

where is located the PyCharm launch script? Is it available in your `$PATH`?

**Comment by netgitdom** [comment]
Hi,

thanks for your answer. I checked my $PATH, the path to the shell scripts wasn't in it m) 
I created two symlinks inside
/usr/local/bin/

pycharm -> /Users/XXXX/OneDrive/Konfigs/JetBrainsShellFolder/pycharm

and the same for DataGrip and it works :-)

Thanks a lot for pointing me in the right direction and your fantastic workflow.

**Comment by bchatard** [comment]
You're welcome :)
